# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.daemon = true


#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
minecraft_version = 26.2

minecraft_version_range = (1.21.11, ]

neo_version=26.2.0.82
loader_version_range = [2,)

neo_version_low = 26.0.0-beta

# Mod Properties
mod_version = 1.5.2
mod_id = torohealth
maven_group = net.kairost
mod_name = ToroHealth-Continued
mod_group_id = net.kairost.torohealth
archives_base_name = torohealth-continued
mod_license = GPL3