# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
# After making changes
# gradlew --refresh-dependencies
# To remap the mixin locations:
# gradlew migrateMappings --mappings "1.16.1+build.9"

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.5.1
maven_group = net.kairost
archives_base_name = torohealth-continued

# Dependencies
fabric_version=0.158.0+26.2

# Third Party
modmenu_version = 20.0.0-beta.4
clothconfig_version = 26.2.155